Ft members only
danielufeli/members-only pull request #1
Opened 2021-05-02 21:44 UTC by danielufeli

This branch we built a members only application where users can write anonymous posts. when logged in, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.

2021-05-02 23:20 UTC, sinansevgi requested changes
# Status: Changes Requested :recycle: 

Hello @danielufeli, :wave:

Great Work!, 

The project works well and meets most of the specifications.
I like that you have validations for the post model. Most of the students ignore validations if it is not specifically requested. **Kudos to you** :+1:

However, there are some issues you should check before going further.

## Required Changes 

- [x] There should be NO application logic in the views nor helpers. Views should only display data that they get from the controller. Everything connected with data processing should be encapsulated in models and used in controllers.

- - [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*\_helper.rb)

- - [ ] There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.


> **Resources**
> 
>  - [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
>  - [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
>  - [Rails View Helpers — Best Practices Guide](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
>  - [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright


For more specific issues I left inline comments. 
Please check them :point_down:

-----
You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

2021-05-02 23:20 UTC, sinansevgi commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_user!, except: %i[index new create]
- [x] Only signed-in users should be able to create new posts. Currently, you are excepting  `new` and `create` from authentication.

Please check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from the Odin project.

2021-05-02 23:20 UTC, sinansevgi commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
- [x] Please remove the commented code.

2021-05-02 23:20 UTC, sinansevgi commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build
- [x] This method should initialize an empty post. Therefore you should use `new` action instead of `builder`
Please check the Odin project requirements. ([screentshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png))

2021-05-04 17:45 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @danielufeli  , your project is approved :tada: :tada: :tada: 
You have implemented all requested changes for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2021-05-04 18:09 UTC, merged